# 线上配置文件
# 注意开源时这个文件不要提交、或者不要填真实配置
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.221.116.109:3306/mate-search
    username: mate-search
    password: 3KD37PS5xZN6pTC4
  # session 失效时间
  session:
    timeout: 86400
  redis:
#    host: 124.221.116.109
    host: 127.0.0.1
    port: 6379
    database: 1
server:
  address: 0.0.0.0
